sudo: false
language: ruby
rvm:
- 2.2
branches:
  only:
  - master
install:
- gem install jekyll
script:
- ./buildscripts/deploy.sh
env:
  global:
    secure: arWHFP+aq53GYFUuokg//gbztcZibCvxRCRl0OEimINvKuhqB2DRmwm684jQDbypW/Hn7HR8a4Cs+QWFJPt5XHpJMcDTLZsLrK5xCxLaTKL9n0ib7YpHbJVe/yW64zcWfWYV2QYjBbwHB8APPkTCqXceHF8vIgXsAiMB5EaLiipykGOoTo2oOSBAG0ByHKYYU3SsRYReevnBexg6OlNcI2nrboCb6ve7yJ3//1n7E7etIQXfzu0pyTpMz3K+4KwSb369ArX89VK/oLfHPQylix4kYw/kECuLlxgcefgvxvAK8kI71djbhAaaPRiRrBkeGS/gx2PCdmcdzryARqwIh4yX/iT+4op1pW015TOO0kVk8mpM/8SIAsz2PXe/gGe3I/mqyfOva7ccqUqUWlR0HMsPgzL+3AREVLCS8HPDe9F11ZAKPLprKtw3AdUhO/Xk6edZ9R/VJhvRWNnAiyuffuPjkHNm9Uq/D1ICv9HX7tcB8Ja4mgSsy2M/EkmScMKMrlvJ9Q/Jx7iQWkr2dOFvplt81wZmCHqeGk157g5qPHfJvqVEjD7+5yGkHgHzPNqHiCFoUe+YsSmFo5MhfX79vxlqS0Mg7jJ0oX/YuWSEKV4QWyeKRk04o0BHeJUPWMvDv+GHqKl7DreokX9xYau0vqWMiBDqPKT33Jr7V4U1lx4=
